float:
  any:
  - base_args: ['@metric']
    constructor: Nsg
    disabled: false
    docker_tag: ann-benchmarks-nsg
    module: ann_benchmarks.algorithms.nsg
    name: nsg
    run_groups:
      nsg:
        args: 
          KNN_K: [200]
          KNN_L: [200]
          KNN_iter: [10]
          KNN_S: [10]
          KNN_R: [100]
          NSG_L: [40]
          NSG_R: [50]
          NSG_C: [500]
          # SEARCH_L: [10 , 20 , 40 , 60 , 80 , 100]
        # query_args: [[10, 20, 30, 40, 60, 80, 120, 200, 400, 600, 800]]
        query_args: [[10 , 20  , 40  , 80 , 100] , [1.0 , 1.2 , 1.5 , 2]]
